# entitlement resources
# replace instances of ibmadmin with another name of your choice
# when applying this file, be sure to be in the ibmadmin-modres-entitlement Project
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: ibmadmin-modres-devchan
  labels:
    app: ibmadmin-modreschan
spec:
  type: Namespace
  pathname: ibmadmin-modres-entitlement
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: devchan-ibmadmin-modreschan-deployment
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: ibmadmin-modreschan
    component: main
    package: ibmadmin-modres
spec:
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: devchan-ibmadmin-modreschan-deployment
      labels:
        app: ibmadmin-modreschan
    spec:
      selector:
        matchLabels:
          app: ibmadmin-modreschan
          release: ibmadmin-modres-devchan
          tier: frontend
      replicas: 1
      template:
        metadata:
          labels:
            app: ibmadmin-modreschan
            release: ibmadmin-modres-devchan
            tier: frontend
        spec:
          containers:
            - name: frontend
              image: "kpostreich/modresort:1.0"
              imagePullPolicy: Always
              ports:
                - containerPort: 9080
              env:
              - name: GET_HOSTS_FROM
                value: dns
              - name: WLP_LOGGING_CONSOLE_FORMAT
                value: json
              - name: WLP_LOGGING_CONSOLE_LOGLEVEL
                value: info
              - name: WLP_LOGGING_CONSOLE_SOURCE
                value: message,trace,accessLog,ffdc
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: devchan-ibmadmin-modreschan-service
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: ibmadmin-modreschan
    component: main
    package: ibmadmin-modres
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: devchan-ibmadmin-modreschan-service
      labels:
        app: ibmadmin-modreschan
    spec:
      type: NodePort
      ports:
        - port: 9080
      selector:
        app: ibmadmin-modreschan
        release: ibmadmin-modres-devchan
        tier: frontend
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: devchan-ibmadmin-modreschan-route
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: ibmadmin-modreschan
    component: main
    package: ibmadmin-modres
spec:
  template:
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: devchan-ibmadmin-modreschan-route
      name: ibmadmin-modres
    spec:
      host: ibmadmin-modres-default.10.0.10.2.nip.io
      port:
        targetPort: 9080
      subdomain: ""
      to:
        kind: Service
        name: devchan-ibmadmin-modreschan-service
        weight: 100
      wildcardPolicy: None